authentication:
  # The default is false. Set to true to enable any HTTP client that can
  # connect to _read_. An API key is still required to write.
  allow_anonymous_access: true
  single_user_api_key: ${TILED_SINGLE_USER_API_KEY}
trees:
  - path: /
    tree: catalog
    args:

      uri: /scratch/dvp85458/tiled/catalog2.db
      readable_storage: 
        - "/scratch/dvp85458/tiled/data"
        - "/dls/tmp/mlex/mlex_tomo_framework/data/tiled_storage"
        - "/dls/k11/data/2024/mg37376-1"
      writable_storage: "/dls/k11/data/2024/mg37376-1/processing/tiled_storage"
      # This creates the database if it does not exist. This is convenient, but in
      # a horizonally-scaled deployment, this can be a race condition and multiple
      # containers may simultanouesly attempt to create the database.
      # If that is a problem, set this to false, and run:
      #
      # tiled catalog init URI
      #
      # separately.
      init_if_not_exists: true
uvicorn:
  host: 0.0.0.0
  port: 8000
object_cache:
  available_bytes: 0
metrics: 
  prometheus: false